// Code generated by "stringer -type=ObjectType -trimprefix=Obj"; DO NOT EDIT.

package pack

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ObjNone-0]
	_ = x[ObjCommit-1]
	_ = x[ObjTree-2]
	_ = x[ObjBlob-3]
	_ = x[ObjTag-4]
	_ = x[ObjFake-5]
	_ = x[ObjOfsDelta-6]
	_ = x[ObjRefDelta-7]
	_ = x[ObjAny-8]
	_ = x[ObjMax-9]
}

const _ObjectType_name = "NoneCommitTreeBlobTagFakeOfsDeltaRefDeltaAnyMax"

var _ObjectType_index = [...]uint8{0, 4, 10, 14, 18, 21, 25, 33, 41, 44, 47}

func (i ObjectType) String() string {
	if i < 0 || i >= ObjectType(len(_ObjectType_index)-1) {
		return "ObjectType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ObjectType_name[_ObjectType_index[i]:_ObjectType_index[i+1]]
}
